/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWeeklyRouteImport } from './routes/_app/weekly'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppComicComicIdRouteImport } from './routes/_app/comic/$comicId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeeklyRoute = AppWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppComicComicIdRoute = AppComicComicIdRouteImport.update({
  id: '/comic/$comicId',
  path: '/comic/$comicId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/favorites': typeof AppFavoritesRoute
  '/me': typeof AppMeRoute
  '/weekly': typeof AppWeeklyRoute
  '/comic/$comicId': typeof AppComicComicIdRoute
}
export interface FileRoutesByTo {
  '/favorites': typeof AppFavoritesRoute
  '/me': typeof AppMeRoute
  '/weekly': typeof AppWeeklyRoute
  '/': typeof AppIndexRoute
  '/comic/$comicId': typeof AppComicComicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/me': typeof AppMeRoute
  '/_app/weekly': typeof AppWeeklyRoute
  '/_app/': typeof AppIndexRoute
  '/_app/comic/$comicId': typeof AppComicComicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites' | '/me' | '/weekly' | '/comic/$comicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/favorites' | '/me' | '/weekly' | '/' | '/comic/$comicId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/favorites'
    | '/_app/me'
    | '/_app/weekly'
    | '/_app/'
    | '/_app/comic/$comicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/weekly': {
      id: '/_app/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof AppWeeklyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comic/$comicId': {
      id: '/_app/comic/$comicId'
      path: '/comic/$comicId'
      fullPath: '/comic/$comicId'
      preLoaderRoute: typeof AppComicComicIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppMeRoute: typeof AppMeRoute
  AppWeeklyRoute: typeof AppWeeklyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComicComicIdRoute: typeof AppComicComicIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavoritesRoute: AppFavoritesRoute,
  AppMeRoute: AppMeRoute,
  AppWeeklyRoute: AppWeeklyRoute,
  AppIndexRoute: AppIndexRoute,
  AppComicComicIdRoute: AppComicComicIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
